"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { API_BASE_URL, fetchComTimeout } from "@/lib/api-config";

const auth = () => ({ Authorization: `Bearer ${localStorage.getItem("accessToken") ?? ""}` });
const field = "mt-1 w-full rounded-xl border bg-background px-3 py-2.5 text-sm";
const sectionsOf = (course: any) => course?.sections ?? (course?.units ? [{ id: "conteudo-legado", title: "Conteúdo principal", description: "Seção criada automaticamente para o conteúdo existente.", isPlacement: false, units: course.units }] : []);

function Message({ error }: { error: string }) { return error ? <p className="mt-4 rounded-xl bg-red-500/10 p-3 text-sm font-bold text-red-600">{error}</p> : null; }
function useCourse(id: string) {
  const [course, setCourse] = useState<any>(); const [error, setError] = useState("");
  const load = useCallback(() => fetchComTimeout(`${API_BASE_URL}/admin/courses/${id}`, { headers: auth() }).then(async r => { if (!r.ok) throw new Error((await r.json().catch(() => null))?.message ?? "Não foi possível carregar o curso."); return r.json(); }).then(setCourse).catch(e => setError(e.message)), [id]);
  useEffect(() => { void load(); }, [load]); return { course, error, load };
}

export function CoursesTable() {
  const [courses, setCourses] = useState<any[]>([]); const [error, setError] = useState("");
  useEffect(() => { fetchComTimeout(`${API_BASE_URL}/admin/courses`, { headers: auth() }).then(async r => { if (!r.ok) throw new Error("Não foi possível carregar os cursos."); return r.json(); }).then(setCourses).catch(e => setError(e.message)); }, []);
  return <section className="py-8"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-wider text-primary">Cadastro de conteúdo</p><h1 className="mt-1 text-4xl font-black">Cursos</h1><p className="mt-2 text-muted-foreground">Escolha um curso para gerenciar sua estrutura e suas aulas.</p></div><Link href="/admin/cursos/novo" className="rounded-xl bg-primary px-4 py-3 text-sm font-black text-primary-foreground">Novo curso</Link></header><Message error={error}/><div className="mt-6 overflow-hidden rounded-3xl border bg-card"><table className="w-full text-left"><thead className="bg-muted/50 text-xs uppercase text-muted-foreground"><tr><th className="p-4">Curso</th><th className="p-4">Estrutura</th><th className="p-4 text-right">Ação</th></tr></thead><tbody>{courses.map(course => <tr key={course.id} className="border-t"><td className="p-4"><div className="flex items-center gap-3">{course.logoUrl ? <img src={course.logoUrl} alt="" className="size-11 rounded-xl object-cover"/> : <span className="grid size-11 place-items-center rounded-xl bg-primary/10 font-black text-primary">{course.name.slice(0,1)}</span>}<div><b>{course.name}</b><p className="text-xs text-muted-foreground">{course.slug}</p></div></div></td><td className="p-4 text-sm text-muted-foreground">{course._count?.sections ?? 0} seções · {course._count?.units ?? 0} unidades</td><td className="p-4 text-right"><Link href={`/admin/cursos/${course.id}`} className="inline-block rounded-xl bg-primary px-4 py-2 text-sm font-black text-primary-foreground">Gerenciar</Link></td></tr>)}</tbody></table>{!courses.length && <p className="p-6 text-sm text-muted-foreground">Nenhum curso disponível.</p>}</div></section>;
}

export function NewCourseForm() {
  const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); setSaving(true); const response = await fetchComTimeout(`${API_BASE_URL}/admin/courses`, { method: "POST", headers: { "Content-Type": "application/json", ...auth() }, body: JSON.stringify({ name: f.get("name"), slug: f.get("slug"), logoUrl: f.get("logoUrl") || undefined, description: f.get("description") || undefined, icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="currentColor" d="M4 3h16v18H4z"/></svg>' }) }); setSaving(false); if (!response.ok) { const body = await response.json().catch(() => null); setError(body?.message ?? "Não foi possível salvar o curso."); return; } location.assign("/admin/cursos"); };
  return <section className="py-8"><Link href="/admin/cursos" className="text-sm font-black text-primary">← Cursos</Link><h1 className="mt-4 text-4xl font-black">Novo curso</h1><p className="mt-2 text-muted-foreground">Preencha as informações que os alunos verão antes de iniciar a trilha.</p><form onSubmit={submit} className="mt-6 max-w-2xl space-y-5 rounded-3xl border bg-card p-6"><label className="block text-sm font-black">Nome do curso<input required name="name" placeholder="Ex.: JavaScript" className={field}/></label><label className="block text-sm font-black">Identificador (slug)<input required name="slug" pattern="[a-z0-9-]+" placeholder="Ex.: javascript" className={field}/><span className="mt-1 block text-xs font-normal text-muted-foreground">Use apenas letras minúsculas, números e hífens.</span></label><label className="block text-sm font-black">URL da logo ou imagem<input name="logoUrl" type="url" placeholder="https://..." className={field}/></label><label className="block text-sm font-black">Descrição<input name="description" placeholder="O que o aluno vai aprender?" className={field}/></label><Message error={error}/><button disabled={saving} className="rounded-xl bg-primary px-5 py-3 text-sm font-black text-primary-foreground">{saving ? "Salvando…" : "Criar curso"}</button></form></section>;
}

export function CourseSections({ courseId }: { courseId: string }) {
  const { course, error, load } = useCourse(courseId); const [saving, setSaving] = useState(false);
  const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); setSaving(true); await fetchComTimeout(`${API_BASE_URL}/admin/courses/${courseId}/sections`, { method: "POST", headers: { "Content-Type": "application/json", ...auth() }, body: JSON.stringify({ title: f.get("title"), description: f.get("description") || undefined, isPlacement: f.get("isPlacement") === "on" }) }); setSaving(false); e.currentTarget.reset(); load(); };
  if (!course) return <section className="py-8">Carregando curso…<Message error={error}/></section>;
  const sections = sectionsOf(course);
  return <section className="py-8"><Link href="/admin/cursos" className="text-sm font-black text-primary">← Todos os cursos</Link><header className="mt-4 flex items-center gap-3"><img src={course.logoUrl || "/icon-only.svg"} alt="" className="size-14 rounded-2xl object-cover"/><div><h1 className="text-3xl font-black">{course.name}</h1><p className="text-sm text-muted-foreground">Seções e nivelamento do curso.</p></div></header><form onSubmit={submit} className="mt-6 grid gap-4 rounded-3xl border bg-card p-5 md:grid-cols-3"><label className="block text-sm font-black">Nome da seção<input required name="title" placeholder="Ex.: Fundamentos" className={field}/></label><label className="block text-sm font-black">Descrição<input name="description" placeholder="Objetivo desta seção" className={field}/></label><label className="flex items-end gap-2 pb-3 text-sm font-black"><input name="isPlacement" type="checkbox"/> Esta seção é de nivelamento</label><div className="md:col-span-3"><button disabled={saving} className="rounded-xl bg-primary px-4 py-3 text-sm font-black text-primary-foreground">{saving ? "Criando…" : "Adicionar seção"}</button></div></form><div className="mt-6 overflow-hidden rounded-3xl border bg-card"><table className="w-full text-left"><thead className="bg-muted/50 text-xs uppercase text-muted-foreground"><tr><th className="p-4">Seção</th><th className="p-4">Nivelamento</th><th className="p-4">Unidades</th><th className="p-4 text-right">Ação</th></tr></thead><tbody>{sections.map((section: any) => <tr key={section.id} className="border-t"><td className="p-4"><b>{section.title}</b><p className="text-xs text-muted-foreground">{section.description || "Sem descrição"}</p></td><td className="p-4 text-sm">{section.isPlacement ? "Sim" : "Não"}</td><td className="p-4 text-sm">{section.units?.length ?? 0}</td><td className="p-4 text-right"><Link className="rounded-xl bg-primary px-4 py-2 text-sm font-black text-primary-foreground" href={`/admin/cursos/${courseId}/secoes/${section.id}`}>Gerenciar</Link></td></tr>)}</tbody></table></div></section>;
}

export function SectionUnits({ courseId, sectionId }: { courseId: string; sectionId: string }) {
  const { course, error, load } = useCourse(courseId); const section = sectionsOf(course).find((x: any) => x.id === sectionId); const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f=new FormData(e.currentTarget); await fetchComTimeout(`${API_BASE_URL}/admin/units`, { method:"POST", headers:{"Content-Type":"application/json",...auth()}, body:JSON.stringify({languageId:courseId,sectionId,title:f.get("title")}) }); e.currentTarget.reset(); load(); };
  if (!section) return <section className="py-8">Carregando seção…<Message error={error}/></section>;
  return <section className="py-8"><Link href={`/admin/cursos/${courseId}`} className="text-sm font-black text-primary">← Seções</Link><h1 className="mt-4 text-3xl font-black">{section.title}</h1><p className="mt-1 text-muted-foreground">Unidades desta seção.</p><form onSubmit={submit} className="mt-5 flex max-w-xl gap-3 rounded-3xl border bg-card p-5"><label className="flex-1 text-sm font-black">Nome da unidade<input name="title" required placeholder="Ex.: Variáveis" className={field}/></label><button className="mt-6 h-11 rounded-xl bg-primary px-4 text-sm font-black text-primary-foreground">Adicionar</button></form><div className="mt-6 overflow-hidden rounded-3xl border bg-card">{section.units.map((unit:any) => <div className="flex items-center justify-between border-b p-4 last:border-0" key={unit.id}><div><b>{unit.title}</b><p className="text-xs text-muted-foreground">{unit.lessons.length} aulas</p></div><Link className="rounded-xl bg-primary px-4 py-2 text-sm font-black text-primary-foreground" href={`/admin/cursos/${courseId}/secoes/${sectionId}/unidades/${unit.id}`}>Gerenciar</Link></div>)}</div></section>;
}

export function UnitLessons({ courseId, sectionId, unitId }: { courseId: string; sectionId: string; unitId: string }) {
  const { course, error, load } = useCourse(courseId); const unit = sectionsOf(course).find((x:any)=>x.id===sectionId)?.units.find((x:any)=>x.id===unitId); const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await fetchComTimeout(`${API_BASE_URL}/admin/lessons`,{method:"POST",headers:{"Content-Type":"application/json",...auth()},body:JSON.stringify({unitId,title:f.get("title"),xpReward:Number(f.get("xpReward")),stageCount:Number(f.get("stageCount")),introduction:[]})});e.currentTarget.reset();load();}; if(!unit)return <section className="py-8">Carregando unidade…<Message error={error}/></section>;
  return <section className="py-8"><Link href={`/admin/cursos/${courseId}/secoes/${sectionId}`} className="text-sm font-black text-primary">← Unidades</Link><h1 className="mt-4 text-3xl font-black">{unit.title}</h1><form onSubmit={submit} className="mt-5 grid max-w-3xl gap-4 rounded-3xl border bg-card p-5 md:grid-cols-3"><label className="text-sm font-black md:col-span-3">Título da aula<input required name="title" placeholder="Ex.: Declarando variáveis" className={field}/></label><label className="text-sm font-black">XP da aula<input required name="xpReward" type="number" defaultValue="10" min="0" className={field}/></label><label className="text-sm font-black">Quantidade de etapas<input required name="stageCount" type="number" defaultValue="2" min="1" className={field}/></label><div className="flex items-end"><button className="rounded-xl bg-primary px-4 py-3 text-sm font-black text-primary-foreground">Adicionar aula</button></div></form><div className="mt-6 overflow-hidden rounded-3xl border bg-card">{unit.lessons.map((lesson:any)=><div className="flex items-center justify-between border-b p-4 last:border-0" key={lesson.id}><div><b>{lesson.title}</b><p className="text-xs text-muted-foreground">{lesson.stageCount} etapas · {lesson.xpReward} XP</p></div><Link className="rounded-xl bg-primary px-4 py-2 text-sm font-black text-primary-foreground" href={`/admin/cursos/${courseId}/secoes/${sectionId}/unidades/${unitId}/aulas/${lesson.id}`}>Gerenciar</Link></div>)}</div></section>;
}

export function LessonStages({ courseId, sectionId, unitId, lessonId }: { courseId:string; sectionId:string; unitId:string; lessonId:string }) { const { course,error,load }=useCourse(courseId); const lesson=sectionsOf(course).find((x:any)=>x.id===sectionId)?.units.find((x:any)=>x.id===unitId)?.lessons.find((x:any)=>x.id===lessonId); const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await fetchComTimeout(`${API_BASE_URL}/admin/lessons/${lessonId}/exercises`,{method:"POST",headers:{"Content-Type":"application/json",...auth()},body:JSON.stringify({type:"MULTIPLE_CHOICE",prompt:f.get("prompt"),content:{stage:Number(f.get("stage")),options:String(f.get("options")).split("\n").filter(Boolean),correctAnswer:f.get("answer")}})});e.currentTarget.reset();load();};if(!lesson)return <section className="py-8">Carregando aula…<Message error={error}/></section>;return <section className="py-8"><Link href={`/admin/cursos/${courseId}/secoes/${sectionId}/unidades/${unitId}`} className="text-sm font-black text-primary">← Aulas</Link><h1 className="mt-4 text-3xl font-black">{lesson.title}</h1><p className="mt-1 text-muted-foreground">Etapas e exercícios da aula.</p><form onSubmit={submit} className="mt-5 max-w-3xl space-y-4 rounded-3xl border bg-card p-5"><label className="block text-sm font-black">Pergunta<textarea required name="prompt" className={field}/></label><label className="block text-sm font-black">Etapa<input name="stage" type="number" min="1" defaultValue="1" className={field}/></label><label className="block text-sm font-black">Alternativas (uma por linha)<textarea required name="options" className={field}/></label><label className="block text-sm font-black">Resposta correta<input required name="answer" className={field}/></label><button className="rounded-xl bg-primary px-4 py-3 text-sm font-black text-primary-foreground">Adicionar etapa</button></form><div className="mt-6 space-y-3">{lesson.exercises.map((item:any,index:number)=><article className="rounded-2xl border bg-card p-4" key={item.id}><p className="text-xs font-black text-primary">ETAPA {item.content?.stage ?? index+1}</p><b className="mt-1 block">{item.prompt}</b></article>)}</div></section>; }
